import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { ContactBand } from "@/components/site/contact-band";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({
  title: "About Find Sherpas",
  description:
    "A boutique agency focused on ecommerce search, informed by in-house experience at businesses serving millions of customers across European markets.",
  path: "/about",
  absoluteTitle: true,
});

export default function AboutPage() {
  return (
    <>
      <section className="fs-page-hero">
        <h1>
          Search is
          <br />
          our whole focus.
        </h1>
        <p>
          Find Sherpas is a boutique agency for ecommerce teams that want more
          from on-site search. We bring analysis, product judgment and practical
          delivery into the same conversation.
        </p>
      </section>
      <section className="fs-section fs-about-statement">
        <h2>
          The experience of owning search.
          <br />
          Applied to yours.
        </h2>
        <p>
          A search problem rarely belongs to one setting or one team. Product
          data, ranking rules, analytics and interface decisions all play a
          part. Understanding the connections is what lets us turn a broad
          problem into work your team can act on.
        </p>
        <p>
          We work with the search you already run, from the first assessment to
          recurring improvements. The depth of our involvement follows your
          priorities and your team’s capacity to deliver.
        </p>
      </section>
      <section className="fs-section fs-history">
        <div>
          <h2>
            Experience behind
            <br />
            the agency.
          </h2>
          <p className="fs-history-note">
            Find Sherpas draws on founder Michal Pekarcik’s prior in-house
            experience. These are the environments behind the practice, rather
            than agency client projects.
          </p>
        </div>
        <div className="fs-prose">
          <p>
            That experience spans businesses with approximately €50M, €200M and
            €1.2B in annual revenue, serving millions of customers across 25+
            European countries.
          </p>
          <p>
            It includes work at Footshop, Dr. Max and Groupon, with search
            technologies including Elasticsearch, Algolia, Luigi’s Box,
            Constructor, Bloomreach Discovery, Nosto, Athos Commerce, Coveo
            and in-house engines.
          </p>
          <p>
            Different catalogues, languages and commercial contexts call for
            different decisions. We bring that perspective to the search
            challenges of a growing ecommerce business.
          </p>
          <p className="fs-history-note">
            The revenue figures describe the scale of those businesses during
            that experience. They are not revenue generated by Find Sherpas or
            current financial figures.
          </p>
        </div>
      </section>
      <section className="fs-section fs-intro fs-about-fit">
        <h2>
          A specialist partner
          <br />
          for your next stage.
        </h2>
        <div className="fs-prose">
          <p>
            We typically work with ecommerce businesses around $10–100M in
            annual revenue, primarily in Europe and the UK. Our conversations
            often start with the person responsible for product, technology or
            ecommerce performance.
          </p>
          <p>
            You may already have a capable engine and a strong engineering team.
            We help them identify which search problems deserve attention,
            specify the changes and evaluate the result.
          </p>
          <Link href="/approach" className="fs-text-link">
            How we work together <ArrowUpRight size={20} aria-hidden="true" />
          </Link>
        </div>
        <dl className="fs-about-range" aria-label="The scale we work across">
          <div>
            <dt>Typical annual company revenue, USD</dt>
            <dd>$10–100M</dd>
          </div>
          <div>
            <dt>Languages worked across</dt>
            <dd>15</dd>
          </div>
          <div>
            <dt>Users per business</dt>
            <dd>100K–50M</dd>
          </div>
          <div>
            <dt>Search platforms &amp; engines</dt>
            <dd>9</dd>
          </div>
        </dl>
      </section>
      <ContactBand />
    </>
  );
}
